from postgres.p_dades import postgres_credencials
from postgres.p_connexio import conn
from postgres.interaccio import afegir_usuari
from postgres.interaccio import afegir_tweet
from postgres.interaccio import tweet_normal
from postgres.interaccio import tweet_usuaris
from postgres.interaccio import tweet_resposta
from postgres.interaccio import afegir_seguidor
from postgres.interaccio import afegir_unfollow
from postgres.interaccio import afegir_bloqueig
from postgres.interaccio import afegir_estadistiques
from postgres.interaccio import actualitzar_estadistiques
from postgres.interaccio import bloquejar_usuari
from postgres.interaccio import data_actual
from postgres.interaccio import hora_actual